name: CI
on:
  push:
    branches: [ PR-* ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          version: 12
      - name: Install npm deps
        run: npm ci
      - name: Run unit tests
        run: npm test
